<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
$count=(int)db()->query('SELECT COUNT(*) FROM admins')->fetchColumn();
$done=$count>0;$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'&&!$done){csrf_verify();$username=trim((string)($_POST['username']??''));$password=(string)($_POST['password']??'');$confirm=(string)($_POST['confirm_password']??'');if(!preg_match('/^[A-Za-z0-9_.-]{4,50}$/',$username))$errors[]='نام کاربری باید ۴ تا ۵۰ کاراکتر و فقط شامل حروف انگلیسی، عدد، نقطه، خط تیره یا زیرخط باشد.';if(strlen($password)<12||!preg_match('/[A-Za-z]/',$password)||!preg_match('/\d/',$password))$errors[]='رمز عبور باید حداقل ۱۲ کاراکتر و شامل حرف و عدد باشد.';if($password!==$confirm)$errors[]='تکرار رمز عبور یکسان نیست.';if(!$errors){try{$q=db()->prepare('INSERT INTO admins(username,password_hash,is_active) VALUES(?,?,1)');$q->execute([$username,password_hash($password,PASSWORD_DEFAULT)]);$done=true;}catch(PDOException $e){$errors[]='ساخت مدیر انجام نشد. لطفاً دوباره تلاش کنید.';}}}
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>راه‌اندازی میرا کافه</title><link rel="stylesheet" href="<?=url('assets/css/admin.css')?>"></head><body class="auth-page"><main class="auth-card setup-card"><div class="auth-logo"><b>MIRA</b><span>SETUP</span></div><?php if($done):?><h1>راه‌اندازی کامل شد</h1><div class="alert success">مدیر اولیه وجود دارد و این صفحه غیرفعال است.</div><p class="muted">اکنون فایل <b>setup.php</b> را از هاست حذف کنید.</p><a class="btn primary full" href="<?=url('admin/login.php')?>">ورود به مدیریت</a><?php else:?><p class="kicker">راه‌اندازی یک‌بار مصرف</p><h1>ساخت مدیر اولیه</h1><p class="muted">یک رمز قوی و منحصربه‌فرد انتخاب کنید.</p><?php if($errors):?><div class="alert error"><ul><?php foreach($errors as $e):?><li><?=e($e)?></li><?php endforeach;?></ul></div><?php endif;?><form method="post" class="stack-form"><?=csrf_field()?><label>نام کاربری<input name="username" dir="ltr" autocomplete="username" required></label><label>رمز عبور<input type="password" name="password" minlength="12" autocomplete="new-password" required></label><label>تکرار رمز عبور<input type="password" name="confirm_password" minlength="12" autocomplete="new-password" required></label><button class="btn primary full">ساخت مدیر</button></form><?php endif;?></main></body></html>

