<?php
declare(strict_types=1);
require_admin();
$adminTitle = $adminTitle ?? 'پنل مدیریت';
$current = basename($_SERVER['PHP_SELF'] ?? '');
$flashMessage = pull_flash();
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?= e($adminTitle) ?> | میرا کافه</title><link rel="icon" type="image/svg+xml" href="<?= url('assets/images/favicon.svg') ?>"><link rel="stylesheet" href="<?= url('assets/css/admin.css') ?>?v=2.0.0"><link rel="stylesheet" href="<?= url('assets/css/admin-theme.css') ?>?v=2.0.0"><link rel="stylesheet" href="<?= url('assets/css/admin-enhancements.css') ?>?v=1.0.0"><script src="<?= url('assets/js/admin.js') ?>?v=1.0.0" defer></script></head><body>
<header class="admin-top"><a class="admin-brand" href="<?= url('admin/') ?>"><b>MIRA</b><span><?= e($adminTitle) ?></span></a><button class="nav-toggle" type="button" aria-label="نمایش منو" aria-expanded="false">☰</button><nav class="admin-nav" aria-label="منوی مدیریت"><a class="<?= $current === 'index.php' ? 'active' : '' ?>" href="<?= url('admin/') ?>">پیشخوان</a><a class="<?= in_array($current,['products.php','product-edit.php'],true) ? 'active' : '' ?>" href="<?= url('admin/products.php') ?>">محصولات</a><a class="<?= $current === 'categories.php' ? 'active' : '' ?>" href="<?= url('admin/categories.php') ?>">دسته‌بندی‌ها</a><a class="<?= $current === 'analytics.php' ? 'active' : '' ?>" href="<?= url('admin/analytics.php') ?>">آمار</a><a class="<?= $current === 'qr-card.php' ? 'active' : '' ?>" href="<?= url('admin/qr-card.php') ?>">کارت QR</a><a class="<?= $current === 'settings.php' ? 'active' : '' ?>" href="<?= url('admin/settings.php') ?>">تنظیمات</a><a class="<?= $current === 'password.php' ? 'active' : '' ?>" href="<?= url('admin/password.php') ?>">رمز عبور</a><a href="<?= url('') ?>" target="_blank">دیدن منو ↗</a><a class="logout" href="<?= url('admin/logout.php') ?>">خروج</a></nav></header>
<main class="admin-main"><div class="page-head"><div><p>مدیریت میرا کافه</p><h1><?= e($adminTitle) ?></h1></div></div><?php if ($flashMessage): ?><div class="alert <?= e($flashMessage['type']) ?>" role="status"><?= e($flashMessage['message']) ?></div><?php endif; ?>
