<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/bootstrap.php'; require_admin();
$days=30;
$summary=db()->query("SELECT COALESCE(SUM(CASE WHEN event_type='view' THEN event_count END),0) views, COALESCE(SUM(CASE WHEN event_type='product' THEN event_count END),0) interactions FROM analytics_daily WHERE event_date>=CURDATE()-INTERVAL 29 DAY")->fetch();
$popular=db()->query("SELECT p.name_fa,c.name_fa category_name,SUM(a.event_count) total FROM analytics_daily a JOIN products p ON p.id=a.product_id JOIN categories c ON c.id=p.category_id WHERE a.event_type='product' AND a.event_date>=CURDATE()-INTERVAL 29 DAY GROUP BY p.id,p.name_fa,c.name_fa ORDER BY total DESC LIMIT 10")->fetchAll();
$daily=db()->query("SELECT event_date,SUM(event_count) total FROM analytics_daily WHERE event_type='view' AND event_date>=CURDATE()-INTERVAL 13 DAY GROUP BY event_date ORDER BY event_date")->fetchAll();
$max=max(1,...array_map(fn($r)=>(int)$r['total'],$daily));
$adminTitle='آمار بازدید';require __DIR__.'/_header.php';
?><section class="stats"><article><span>بازدید ۳۰ روز اخیر</span><strong><?=fa_digits((int)$summary['views'])?></strong></article><article><span>مشاهده جزئیات محصولات</span><strong><?=fa_digits((int)$summary['interactions'])?></strong></article><article><span>نرخ تعامل</span><strong><?=fa_digits($summary['views']?round($summary['interactions']/$summary['views']*100):0)?>٪</strong></article></section><div class="analytics-grid"><section class="panel"><div class="panel-title"><div><h2>روند بازدید</h2><p>۱۴ روز اخیر؛ بدون ذخیره اطلاعات هویتی کاربران</p></div></div><div class="mini-chart"><?php if(!$daily):?><p class="empty">هنوز داده‌ای ثبت نشده است.</p><?php endif;?><?php foreach($daily as $d):?><div style="--h:<?=max(5,round($d['total']/$max*100))?>%"><span><?=fa_digits($d['total'])?></span><i></i><small><?=fa_digits(date('m/d',strtotime($d['event_date'])))?></small></div><?php endforeach;?></div></section><section class="panel"><div class="panel-title"><div><h2>محبوب‌ترین محصولات</h2><p>بر اساس بازکردن ترکیبات یا انتخاب پیشنهادها</p></div></div><ol class="popular-list"><?php foreach($popular as $i=>$p):?><li><b><?=fa_digits($i+1)?></b><span><strong><?=e($p['name_fa'])?></strong><small><?=e($p['category_name'])?></small></span><em><?=fa_digits($p['total'])?></em></li><?php endforeach;?><?php if(!$popular):?><li class="empty">هنوز تعاملی ثبت نشده است.</li><?php endif;?></ol></section></div><?php require __DIR__.'/_footer.php';?>
