<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/bootstrap.php';require_admin();
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 csrf_verify();$action=(string)($_POST['action']??'save');$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);
 if($action==='delete'&&$id){$s=db()->prepare('SELECT COUNT(*) FROM products WHERE category_id=?');$s->execute([$id]);if((int)$s->fetchColumn()>0){flash('error','این دسته محصول دارد؛ ابتدا محصولاتش را جابه‌جا یا حذف کنید.');}else{db()->prepare('DELETE FROM categories WHERE id=?')->execute([$id]);flash('success','دسته حذف شد.');}redirect('admin/categories.php');}
 $name=trim((string)($_POST['name_fa']??''));$slug=trim((string)($_POST['slug']??''));$sort=filter_var($_POST['sort_order']??0,FILTER_VALIDATE_INT);$active=request_bool('is_active');
 if($name===''||mb_strlen($name)>100)$errors[]='نام دسته الزامی است.';if(!preg_match('/^[a-z0-9-]{2,100}$/',$slug))$errors[]='شناسه باید با حروف انگلیسی کوچک، عدد و خط تیره باشد.';
 if(!$errors){try{if($id){db()->prepare('UPDATE categories SET name_fa=?,slug=?,sort_order=?,is_active=? WHERE id=?')->execute([$name,$slug,$sort,$active,$id]);flash('success','دسته ویرایش شد.');}else{db()->prepare('INSERT INTO categories(name_fa,slug,sort_order,is_active) VALUES(?,?,?,?)')->execute([$name,$slug,$sort,$active]);flash('success','دسته اضافه شد.');}redirect('admin/categories.php');}catch(PDOException $e){$errors[]='این شناسه قبلاً استفاده شده است.';}}
}
$categories=db()->query('SELECT c.*,COUNT(p.id) product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.id ORDER BY c.sort_order,c.id')->fetchAll();$adminTitle='دسته‌بندی‌ها';require __DIR__.'/_header.php';
?><?php if($errors):?><div class="alert error"><?=e(implode(' ',$errors))?></div><?php endif;?><details class="panel add-panel" <?=!empty($errors)?'open':''?>><summary>+ افزودن دسته جدید</summary><form method="post" class="compact-form"><?=csrf_field()?><input type="hidden" name="action" value="save"><label>نام فارسی<input name="name_fa" required maxlength="100"></label><label>شناسه انگلیسی<input name="slug" required pattern="[a-z0-9-]+" dir="ltr" placeholder="hot-coffee"></label><label>ترتیب<input type="number" name="sort_order" min="0" value="0"></label><label class="check"><input type="checkbox" name="is_active" checked> فعال</label><button class="btn primary" type="submit">افزودن</button></form></details><div class="category-list"><?php foreach($categories as $c):?><article class="panel category-row"><form method="post" class="compact-form"><?=csrf_field()?><input type="hidden" name="id" value="<?=(int)$c['id']?>"><input type="hidden" name="action" value="save"><label>نام<input name="name_fa" value="<?=e($c['name_fa'])?>" required></label><label>شناسه<input name="slug" dir="ltr" value="<?=e($c['slug'])?>" pattern="[a-z0-9-]+" required></label><label>ترتیب<input type="number" min="0" name="sort_order" value="<?=(int)$c['sort_order']?>"></label><span class="count"><?=fa_digits($c['product_count'])?> محصول</span><label class="check"><input type="checkbox" name="is_active" <?=$c['is_active']?'checked':''?>> فعال</label><button class="btn small" type="submit">ذخیره</button></form><form method="post" class="inline delete-category" data-confirm="اگر این دسته خالی باشد، حذف می‌شود. ادامه می‌دهید؟"><?=csrf_field()?><input type="hidden" name="id" value="<?=(int)$c['id']?>"><input type="hidden" name="action" value="delete"><button class="btn small danger" type="submit">حذف</button></form></article><?php endforeach;?></div><?php require __DIR__.'/_footer.php';?>

